name: first-gb-actions-workflow
on:
 workflow_dispatch:
 push:
  branches:
    - main
  paths:
    - "ch01/**"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install bats
        run: npm install -g bats
      - name: run bats
        run: bats -v